# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_current_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reports_allowed',
            new_name='monthly_reports_allowed',
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_reports_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_reports_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
