# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10 on 2017-09-05 00:08
from __future__ import unicode_literals

from django.db import migrations, models
=======
# Generated by Django 1.10 on 2017-09-07 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
>>>>>>> 864dc4712996a459723ef14f18b9d8857d5206ec


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.TextField()),
                ('story', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user_tokens', models.TextField()),
=======
            name='FAQnAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
>>>>>>> 864dc4712996a459723ef14f18b9d8857d5206ec
            ],
        ),
    ]
