# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.TextField()),
                ('story', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user_tokens', models.TextField()),
            ],
        ),
    ]
